import type { TemplateQuestion } from '../types/study';

// Universal eSource rules ("Universal Rules across all the sites"), surfaced in
// the preferences template as selectable Yes/No questions. MUST stay in sync
// with the server source of truth at
// protocol-builder-server/src/services/pipeline/universalRules.ts — ids are
// generated as `u-<prefix>-<n>` so both sides agree (the server injects these
// per form; here they drive the UI and any "No" overrides).

interface RuleGroupSeed {
  group: string;
  prefix: string;
  rules: string[];
}

const GROUPS: RuleGroupSeed[] = [
  {
    group: 'Visit Forms',
    prefix: 'visit',
    rules: [
      'Auto-populate visits, forms & procedures from the Schedule of Activities (SoA)',
      'Support unscheduled visits using predefined types (not unlimited free-form)',
      'Provide visit statuses: Planned, Scheduled, In Progress, Completed, Missed, Unscheduled, Early Termination',
      'Visit completion auto-sets status to Completed',
      'Require documentation before closing a Missed visit',
      'Display the visit window to users',
      'Alert when a visit occurs outside the allowed window',
      'Auto-generate protocol deviations for out-of-window visits',
      "Auto-calculate the next visit's target date",
      'Missed visits trigger follow-up notifications',
      'Show all protocol-required assessments for the visit',
      'Display optional assessments separately',
      'Auto-hide assessments not applicable to the visit',
      'Visit completion locks all completed forms',
      'Unresolved data queries block visit completion',
      'Investigator review mandatory before visit completion',
      'Electronic signature required to complete the visit',
      'Visit Form becomes read-only after electronic signature',
      'Provide a dedicated Visit Notes section',
      'Include visit-specific comments',
      'Summarize abnormal findings, AEs & newly added con meds on the Visit Form',
      'Identify missing required procedures before allowing completion',
      'Generate a visit summary for investigator review before e-signature',
      'If Missed, auto-mark all scheduled assessments as Not Performed',
      'If Early Termination, auto-redirect to the Early Termination assessment form',
      'If Unscheduled, show only the selected forms',
      'If outside the protocol window, auto-redirect to a Protocol Deviation form',
      'Warn on any blank source field before visit completion',
    ],
  },
  {
    group: 'Medical History',
    prefix: 'mh',
    rules: [
      'Allow multiple medical history records',
      'Categorize conditions (Cardiovascular, Respiratory, GI, Neurological, Endocrine, Psychiatric, Infectious Disease, Oncology, Other)',
      'Show protocol-specific categories first',
      'Allow custom condition categories',
      'Diagnosis start/end date mandatory (DD-MM-YYYY); allow partial/unknown day & month',
      'Record disease status (Ongoing, Resolved, Stable, Worsening, Unknown)',
      'Auto-highlight clinically significant conditions',
      'Clinically significant conditions trigger eligibility review',
      'Auto-link clinically significant conditions to the referenced assessment',
      'Link Medical History to Concomitant Medications',
      'Link Medical History to Adverse Events',
      'Link Medical History to Surgical History',
      'Auto-populate relevant Physical Examination findings from Medical History',
      'Warn on duplicate medical history entries',
      'Flag diagnosis dates after the Screening Visit',
      'Suggest conditions from uploaded medical records',
      'Support document attachments (discharge summaries, specialist letters)',
    ],
  },
  {
    group: 'Concomitant Medications',
    prefix: 'cm',
    rules: [
      'Allow multiple concomitant medication records per subject',
      'Select medication names from the WHO Drug Dictionary',
      'Allow free-text entry when a medication is not in the dictionary',
      'Show generic and brand names in a single field',
      'Link indication to an existing Medical History condition',
      'Classify route of administration (Oral, Topical, Subcutaneous, …)',
      'Pre-classify dosage strengths, frequencies & units',
      'Medication start/end date with Ongoing toggle mandatory (DD-MM-YYYY); allow partial/unknown',
      'Alert on prohibited medications',
      'Make protocol-specific medication restrictions configurable',
      'Link medications to Medical History conditions',
      'Link medications to Adverse Events',
      'Show newly added medications in the Visit Summary',
      'Dosage modifications create a new version (do not overwrite)',
      'Import medications from EHR when available',
      'List rescue medication separately in the con meds section',
    ],
  },
  {
    group: 'Physical Examination',
    prefix: 'pe',
    rules: [
      'Allow multiple examination records during a visit',
      'Display body systems individually',
      'Include body systems: General Appearance, HEENT, Skin, Respiratory, Cardiovascular, GI, Genitourinary, Musculoskeletal, Neurological, Psychiatric, Lymphatic, Endocrine, Other',
      'Hide body systems not required by the protocol',
      'Allow customizing the body system list',
      'Use Normal/Abnormal selection per body system',
      'Auto-show a comments field for abnormal findings',
      'Require mandatory comments for abnormal findings',
      'Targeted exams allow only protocol-selected body systems',
      'Require investigator review & e-signature on completion',
      'Capture initials of the person performing & scribing the exam',
      'Validate examination dates against visit dates',
      'Abnormal clinically significant findings suggest an Adverse Event entry',
      'Link abnormal findings to Medical History',
      'Alert for protocol-required follow-up procedures from abnormal findings',
      'Show protocol-specific exam instructions beside each body system',
    ],
  },
  {
    group: 'Vital Signs',
    prefix: 'vs',
    rules: [
      'Allow multiple/triplicate Vital Signs during a single visit',
      'Collect: Height, Weight, BMI, Temperature, Heart Rate, Respiratory Rate, Blood Pressure, SpO2, Waist Circumference, Hip Circumference, Other',
      'Make measurement units configurable (mmHg BP, C/F temp, % SpO2)',
      'Support automatic unit conversion (e.g. BMI)',
      'Document measurement method (e.g. oral vs tympanic temperature)',
      'Record body position (Sitting, Standing, Supine, …)',
      'Collect fasting status',
      'Display protocol-defined reference ranges',
      'Alert on out-of-range values',
      'Abnormal temperature suggests an Adverse Event review',
      'Allow uploading supporting documentation',
      'Capture initials of the person performing Vital Signs',
    ],
  },
  {
    group: 'ECG',
    prefix: 'ecg',
    rules: [
      'Allow multiple ECG assessments during a single visit',
      'Record ECG type (e.g. 12-lead)',
      'Require ECG attachment (PDF/image)',
      'Capture parameters: Heart Rate, PR, QRS, QT, QTc, RR, Axis, Rhythm, Other',
      'Auto-calculate QTc when QT and RR are entered',
      'Support multiple QT correction formulas (Bazett, Fridericia)',
      'Use standardized interpretation (Normal; Abnormal NCS; Abnormal CS)',
      'Require mandatory comments for abnormal ECGs',
      'Require e-signature & comment for ECG interpretation',
      'Warn on protocol-defined QT/QTc limits',
      'Block completion when mandatory parameters are missing',
      'Validate ECG timing against study drug administration',
      'Abnormal clinically significant findings suggest an Adverse Event entry',
      'Trigger Protocol Deviation review if required ECG assessments were missed',
    ],
  },
  {
    group: 'Adverse Events',
    prefix: 'ae',
    rules: [
      'Allow multiple Adverse Events per visit',
      'Require a free-text event description',
      'Date & time (24h) required; unknown date NOT allowed',
      'Identify Adverse Events of Special Interest (AESIs) separately',
      'Require severity grading (CTCAE/DAIDS)',
      'Use standardized outcomes (Recovered, Recovering, Ongoing, Fatal, Unknown)',
      'Relationship to Study Drug mandatory',
      'Document action taken with Study Drug',
      'Record additional treatment for the AE',
      'Document hospitalization related to the AE',
      'Link AEs to Study Drug Administration',
      'Link AEs to Concomitant Medications',
      'Link AEs to Medical History',
      'Link AEs to Protocol Deviations',
      'Investigator review & e-signature mandatory before AE completion',
      'Follow-up visits auto-reopen unresolved AEs',
      'Lab/ECG/PE abnormalities suggest Adverse Event creation',
    ],
  },
  {
    group: 'Protocol Deviations',
    prefix: 'pd',
    rules: [
      'Allow multiple Protocol Deviations per subject & visit',
      'Allow manual entry and automatic generation',
      'Auto-link deviations to the corresponding visit',
      'Use a predefined category list (Visit Window, Eligibility, Informed Consent, Study Drug, Lab Assessment, Safety Assessment, Procedure, Subject non-compliance, Site Error, Other)',
      'Require deviation severity (Minor, Major, Critical)',
      'Deviation date required with affected visit type documented',
      'Assess subject safety impact',
      'Require sponsor assessment',
      'Investigator electronic review & signature required',
      'Document corrective & preventive action (CAPA) in the required comments section',
      'Major/Critical deviations notified to local IRB & sponsor within 24 hours',
      'Auto-link deviations to Adverse Events when applicable',
      'Auto-link deviations to Study Drug Administration',
      'Auto-create a deviation for visits outside the protocol window',
      'Missed mandatory assessments auto-generate a deviation draft',
      'Dosing outside protocol limits auto-generates a deviation',
      'Repeated deviations trigger alerts',
    ],
  },
  {
    group: 'Visit Completion',
    prefix: 'vc',
    rules: [
      'Lock completed Visit Completion forms after signature',
      'Require all mandatory forms completed before Visit Completion',
      'Display completion status of each form (MH, ConMed, PE, VS, ECG, Labs, Study Drug, Drug Compliance, PRO/ePRO, AE)',
      'Exclude optional forms from completion validation',
      'Display unresolved Adverse Events',
      'Display unresolved Protocol Deviations',
      'Require investigator e-signature with visit review validation',
      'Auto-generate the next scheduled visit on completion',
      'Carry forward ongoing Medical History conditions',
      'Carry forward ongoing Concomitant Medications',
      'Carry forward ongoing Adverse Events',
      'Auto-notify the next study team member after completion',
      'Generate subject progress notes (completed & remaining visits)',
    ],
  },
  {
    group: 'Patient Questionnaire',
    prefix: 'pro',
    rules: [
      'Support both ePRO and Paper PRO',
      'Allow multiple questionnaires per visit',
      'Auto-assign questionnaires from the SoA by treatment arm',
      'Define who completes it (Subject, Caregiver, Parent/Guardian, Site Staff, Investigator)',
      'Show instructions before completion',
      'Auto-score responses',
      'Warn on inconsistent responses',
      'Mandatory questionnaires block visit completion if incomplete',
    ],
  },
  {
    group: 'Study Drug Administration',
    prefix: 'sd',
    rules: [
      'Allow multiple administration records within the same visit',
      'Create separate records per dose',
      'Auto-populate the Study Drug name from the protocol',
      'Treatment arm determines the displayed study drug',
      'Display the planned dose automatically',
      'Auto-calculate dose (e.g. mg/kg)',
      'Use a predefined route-of-administration list',
      'Record administration site when applicable (e.g. left arm)',
      'Capture administration start/end date & time',
      'Allow dose reductions/interruptions',
      'Require reason for a missed dose; alert when dose is above/below protocol',
      'Dose modifications require investigator approval',
      'Lock the administration form if eligibility is incomplete',
      'Warn on protocol deviations affecting dosing',
      'Link Study Drug Administration to Drug Accountability',
      'Validate kit expiry before administration',
      'Dose interruptions auto-create a Protocol Deviation (if protocol-defined)',
      'Infusion reactions suggest an Adverse Event entry',
      'Assess compliance at every visit',
      'Support compliance methods (Pill/Bottle count, Device log, Infusion/Injection log, Subject diary, eDiary, Electronic monitoring, Investigator assessment, Other)',
      'Allow manual entry or auto-calculation of compliance',
      'Auto-calculate expected doses',
      'Auto-calculate compliance percentage',
      'Use standardized non-compliance reasons (Forgot dose, Subject refusal, Adverse Event, Lost medication, Other)',
      'Document subject counseling/re-education',
      'Alert on protocol-defined minimum compliance thresholds',
    ],
  },
  {
    group: 'Female Participants',
    prefix: 'fp',
    rules: [
      'Capture the protocol-required pregnancy assessment',
      'Flag whether pregnancy testing applies for this visit',
      'Record pregnancy test type per protocol/visit (Urine, Serum, Both)',
      'Capture whether contraception is required by protocol',
      'Record contraceptive method (Abstinence, Oral, Implant, Injection, IUD, Condom, Vasectomy partner, Double barrier, Other)',
      'Confirm contraception is compliant with protocol',
      'Record the contraception start date',
      'Pregnancy result cannot be blank when testing is required',
      'Positive pregnancy result auto-generates a Pregnancy Follow-up form',
      'Require a repeat test when the initial result is invalid',
      'Hide pregnancy fields for male participants unless partner-pregnancy reporting applies',
    ],
  },
  {
    group: 'Demographics',
    prefix: 'dm',
    rules: [
      'Import the Randomization Number from IVRS/IWRS',
      'Auto-calculate age',
      'Alert on protocol minimum/maximum age limits',
      'Show pregnancy/breastfeeding fields only when applicable',
    ],
  },
  {
    group: 'Informed Consent',
    prefix: 'icf',
    rules: [
      'Prevent screening until consent is complete',
      'Prevent study procedures before the consent date/time',
      'Validate that the consent version is current',
      'Ensure all required signatures are present',
      'Auto-populate re-consent after protocol amendments',
      'Require upload of the signed ICF',
      'Require confirmation the participant received a copy',
      'On an amendment requiring re-consent, generate a new re-consent form linked to the prior consent',
      'If consent is not obtained, block all subsequent study forms until valid consent is recorded',
    ],
  },
  {
    group: 'Universal Validation',
    prefix: 'val',
    rules: [
      'Required fields marked with *',
      'No future dates unless the protocol permits',
      'End Date cannot precede Start Date',
      '24-hour time format',
      'Auto-save every 30 seconds',
      'Audit trail enabled; every edit captured',
      'CFR Part 11 compliant electronic signatures',
      'Investigator signature timestamped',
      'User initials captured',
      'Query history retained',
      'Soft delete only',
      'Version history maintained',
      'Read-only after signature',
      'Store date/time in UTC; display per-site timezone',
      'Auto-calculate Age, BMI, QTc, Compliance %',
      'Duplicate detection',
    ],
  },
];

// Flatten to selectable Yes/No questions; default answer "yes".
export const UNIVERSAL_QUESTIONS: TemplateQuestion[] = GROUPS.flatMap((g) =>
  g.rules.map((text, i) => ({
    id: `u-${g.prefix}-${i + 1}`,
    text,
    answerType: 'yesno' as const,
    group: g.group,
    answer: 'yes' as const,
  })),
);

// Group labels in display order (used by the New Build wizard Universal Rules step).
export const UNIVERSAL_GROUPS: string[] = GROUPS.map((g) => g.group);
